#!/bin/bash

#SBATCH --account=oz113
#SBATCH --job-name=VDF_MCMC
#SBATCH --output=log_nu.out
#SBATCH --error=log_nu.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=gferrami@student.unimelb.edu.au
#SBATCH --ntasks=1
#SBATCH --time=20:00:00
#SBATCH --mem-per-cpu=250

srun python3 MCMC_2halo.py 11.5 -22.1 -15.9 5
